### ISSUE TITLE
Межвагонные двери и дверь в кабину не до конца открываются

### ISSUE THREAD

**Issue by Hellss** [metrostroi-repo/metrostroi_beta#18]
Межвагонные двери и дверь в кабину не до конца открываются 
![2016-04-01_18-04-36](https://cloud.githubusercontent.com/assets/16958912/14210978/42e9aeca-f834-11e5-9bde-bea4a9d4775c.png)

**Comment by glebqip** [comment]
А ты посмотри, во что она упирается.

**Comment by glebqip** [comment]
Посмотри во что она упирается
