### ISSUE TITLE
Скины для Еж3

### ISSUE THREAD

**Issue by flydvorkin** [metrostroi-repo/metrostroi_beta#23]
Промежуточный вагон не перекрашивается

**Comment by flydvorkin** [comment]
решение от hellreach скидывал в скайп 100 лет назад. можно было бы в обновлении фикс поставить

**Comment by glebqip** [comment]
03e9fad97b9238560d315936a2b02c460c039a53 Просьба проверить

**Comment by glebqip** [comment]
df9b33a64707ff8114c47aed2c16a5153852ede5
