### ISSUE TITLE
 Поезда отсутствуют переключатели, ошибки модели

### ISSUE THREAD

**Issue by ghost** [metrostroi-repo/metrostroi_beta#27]
Я использую Google Translate , поэтому заранее извиняюсь за ошибки . В любом случае, есть гигантский проблема с бета-версии. Я скачать ZIP, распаковать вещи в правильные папки , и когда я получаю в игре и икру в поезде ни один из переключателей показать. Двери не загружаются , и поезд не работает. В консоли , он говорит, ошибки типа "(имя файла ) здесь должно быть перекомпилирован " . Помогите?

https://gyazo.com/8aef871ecd135fcf5fd2b75407dbb8b9

**Comment by IvanAzarnii** [comment]
Hi, you must set all of your video settings to High. That is the way to solve this problem.

**Comment by ghost** [comment]
Thanks! I did that and it works perfectly, Beta is absolutely EPIC!

**Comment by glebqip** [comment]
Yes, if you don't have switches\buttons\doors on 717 - you need set model quality to very high
