### ISSUE TITLE
[REQUEST] Autodrive Translation Request

### ISSUE THREAD

**Issue by ghost** [metrostroi-repo/metrostroi_beta#36]
Since most of us english players who drive Metrostroi can't read russian, we cannot operate the computerized autodrive systems. I am requesting an english translation option for these autodrive systems. Thanks! If it can't be done, that's okay as well.

**Comment by pixelfelon** [comment]
I have some of the autodrive translations done, but they are a patch (so it couldn't currently just be added to the master branch, as it would replace the Russian version), and they are out of date so parts need to be redone. I'll see about cleaning it up to integrate correctly and doing a pull request.
I'm pretty sure some of the autodrive systems are in English, though.

**Comment by ghost** [comment]
One of them is, but all the other ones aren't. If you could make a patch and update it, that would be wonderful! I love driving the Metrostroi trains but I can't read Russian so thanks! :D

**Comment by pixelfelon** [comment]
https://github.com/pixelfelon/metrostroi_beta
Here it is, currently only PA-M has a translation (it's an option in the train spawner). I'll do a pull request once all of them are translated.
