### ISSUE TITLE
Cannot increase max wagons/trains count on dedicated server

### ISSUE THREAD

**Issue by ghost** [metrostroi-repo/metrostroi_beta#40]
I have tried to do this by editing the files, and I have seen it done before on other Metrostroi servers but for some reason I cannot increase the max wagons count. Help, or is this even possible??

**Comment by pixelfelon** [comment]
Try setting the convars:
metrostroi_maxwagons
metrostroi_maxtrains
metrostroi_maxtrains_onplayer
in the console.
I haven't tested but based on train_spawner.lua this should work.

**Comment by ghost** [comment]
Thank you for the very quick reply and for speaking English, this will help my server. Thanks!

Worked.
