### ISSUE TITLE
Route Signs not working!

### ISSUE THREAD

**Issue by cyber-dream** [metrostroi-repo/metrostroi_beta#5]
_From @flydvorkin on March 24, 2016 6:9_

После обновления 7 марта не работают маршрутные таблички с названиями станций (специальные тоже) на номерных. (На Ема былобы прикольно их тоже сделать).

П.С. Блин, ты раньше говорил что знаешь об этой проблеме и займешся - вот и не писал сюда issue.

_Copied from original issue: glebqip/metrostroi_beta#92_

**Comment by flydvorkin** [comment]
Закройте этот Issue. Глеб починил.
